### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by nibanks** [winshining/H3Client#1]
Hello! 

I'm one of the main devs on MsQuic.

I was just looking through GitHub usages of MsQuic and I found this. The project says it has nginx integration. Is that all working? This is something we've been interested to get working, but hadn't had the time yet. I've been building a side project towards that goal (https://github.com/nibanks/msh3) for quite some time. It seems to overlap a lot with what you have.

Also, I didn't see any license. Do you plan on adding one? MIT would make it much easier to look at the code.

P.S. I would have opened a discussion instead of an issue, but you don't have them enabled.

**Comment by nibanks** [comment]
I reread the readme and are you saying you can connect to NGINX as the server, or that you integrate with NGINX as the server? I'd be super interested to see the second case. The first is still cool though!

**Comment by winshining** [comment]
Hello!

Thank your team for developing such a great project!

I got it worked and the log will be pasted in the next comment.

MIT license was added.

I built the branch `quic` of NGINX as server and I self signed the certificate to test this demo. I just wanted to check if I correctly understood the RFCs of QUIC and HTTP/3. In fact, a lot of codes are from [nginx-quic](https://hg.nginx.org/nginx-quic).

**Comment by winshining** [comment]
winshining@debian:~/workspace/h3/H3Client$ ./H3Client -h demo.h3test.com -p 443
[conn][0x55d38ba58970] Received connection event: 7
[conn][0x55d38ba58970] Received connection event: 10
[conn][0x55d38ba58970] Connected
H3 ref insert static[1] "/index.html"
H3 static[1] lookup ":path":"/"
H3 insert [0] ":path":"/index.html", size:48
H3 ref insert static[0] "demo.h3test.com"
H3 static[0] lookup ":authority":""
H3 insert [1] ":authority":"demo.h3test.com", size:57
H3 ref insert static[95] "h3_over_msquic"
H3 static[95] lookup "user-agent":""
H3 insert [2] "user-agent":"h3_over_msquic", size:56
[strm][0x7faeec015380] Received stream event: 0
[strm][0x7faeec0166f0] Received stream event: 0
[strm][0x7faeec016a50] Received stream event: 0
[strm][0x7faeec016db0] Received stream event: 0
[strm][0x7faeec015380] Received stream event: 2
[strm][0x7faeec0166f0] Received stream event: 2
[strm][0x7faeec0166f0] Received stream event: 2
[strm][0x7faeec016a50] Received stream event: 2
[strm][0x7faeec016db0] Received stream event: 2
[strm][0x7faeec016db0] Received stream event: 2
[conn][0x55d38ba58970] Received connection event: 14
[conn][0x55d38ba58970] Received connection event: 14
[conn][0x55d38ba58970] Peer Stream Started [0x7faeec00ccb0]
[strm][0x7faeec00ccb0] Received
[conn][0x55d38ba58970] Peer Stream Started [0x7faeec045850]
[strm][0x7faeec016db0] Received stream event: 6
[strm][0x7faeec045850] Received
[strm][0x7faeec016db0] Received
[strm][0x7faeec016db0] Request stream received
[strm] Receiving frame completed, type: 1
H3 parse field section prefix
H3 parse prefix int 0
H3 parse prefix int 89
H3 parse field section prefix done insert count:0, sign:0, delta base:89, base:89
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 92
H3 parse prefix int 9
H3 parse literal huff: 1, len: 9
H3 parse literal done "nginx/1.23.4"
H3 parse field lflnr done static[92] "nginx/1.23.4"
H3 static[92] lookup "server":""
H3 parse field representation done
H3 received field line "server": "nginx/1.23.4"
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 6
H3 parse prefix int 22
H3 parse literal huff: 1, len: 22
H3 parse literal done "Mon, 06 Feb 2023 15:18:22 GMT"
H3 parse field lflnr done static[6] "Mon, 06 Feb 2023 15:18:22 GMT"
H3 static[6] lookup "date":""
H3 parse field representation done
H3 received field line "date": "Mon, 06 Feb 2023 15:18:22 GMT"
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 53
H3 parse prefix int 7
H3 parse literal huff: 1, len: 7
H3 parse literal done "text/html"
H3 parse field lflnr done static[53] "text/html"
H3 static[53] lookup "content-type":"text/plain"
H3 parse field representation done
H3 received field line "content-type": "text/html"
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 4
H3 parse prefix int 3
H3 parse literal huff: 0, len: 3
H3 parse literal done "612"
H3 parse field lflnr done static[4] "612"
H3 static[4] lookup "content-length":"0"
H3 parse field representation done
H3 received field line "content-length": "612"
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 10
H3 parse prefix int 22
H3 parse literal huff: 1, len: 22
H3 parse literal done "Tue, 28 Jul 2015 15:54:19 GMT"
H3 parse field lflnr done static[10] "Tue, 28 Jul 2015 15:54:19 GMT"
H3 static[10] lookup "last-modified":""
H3 parse field representation done
H3 received field line "last-modified": "Tue, 28 Jul 2015 15:54:19 GMT"
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 3
H3 parse literal huff: 1, len: 3
H3 parse literal done "etag"
H3 parse prefix int 12
H3 parse literal huff: 1, len: 12
H3 parse literal done ""55b7a5ab-264""
H3 parse field lflln done "etag":""55b7a5ab-264""
H3 parse field representation done
H3 received field line "etag": ""55b7a5ab-264""
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 5
H3 parse literal huff: 1, len: 5
H3 parse literal done "alt-svc"
H3 parse prefix int 16
H3 parse literal huff: 1, len: 16
H3 parse literal done "h3=":443"; ma=86400"
H3 parse field lflln done "alt-svc":"h3=":443"; ma=86400"
H3 parse field representation done
H3 received field line "alt-svc": "h3=":443"; ma=86400"
H3 parse field representation
H3 parse field lflnr
H3 parse prefix int 9
H3 parse literal huff: 1, len: 9
H3 parse literal done "accept-ranges"
H3 parse prefix int 4
H3 parse literal huff: 1, len: 4
H3 parse literal done "bytes"
H3 parse field lflln done "accept-ranges":"bytes"
H3 parse field representation done
H3 received field line "accept-ranges": "bytes"
H3 parse field representation
H3 parse headers done
[strm] Receiving frame completed, type: 0
[strm] ReceiveResponseData: 612
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[strm][0x7faeec016db0] Received stream event: 7
[strm][0x7faeec015380] Received stream event: 6
[strm][0x7faeec015380] Received stream event: 7
[strm][0x7faeec016a50] Received stream event: 6
[strm][0x7faeec016a50] Received stream event: 7
[strm][0x7faeec0166f0] Received stream event: 6
[strm][0x7faeec0166f0] Received stream event: 7
[strm][0x7faeec00ccb0] Received stream event: 7
[strm][0x7faeec045850] Received stream event: 7
[conn][0x55d38ba58970] Received connection event: 7
[conn][0x55d38ba58970] Received connection event: 7
[conn][0x55d38ba58970] Received connection event: 7
[conn][0x55d38ba58970] Received connection event: 7
[conn][0x55d38ba58970] Received connection event: 2
[conn][0x55d38ba58970] All done

**Comment by winshining** [comment]
The log was parsed by GitHub, so attached H3Client.log here.
[H3Client.log](https://github.com/winshining/H3Client/files/10664567/H3Client.log)

`demo.h3test.com` in the log is an arbitrary domain name I set in `/etc/hosts`, which is translated to the IP of my PC.

**Comment by nibanks** [comment]
Thanks for the info!
